/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    CompanyFactory: {
      address: "0x5fbdb2315678afecb367f032d93f642f64180aa3",
      abi: [
        {
          type: "function",
          name: "companies",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "companyOwners",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "createCompany",
          inputs: [
            {
              name: "_companyPublicKey",
              type: "string",
              internalType: "string",
            },
            {
              name: "_name",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getCompanies",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address[]",
              internalType: "address[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "event",
          name: "CompanyCreated",
          inputs: [
            {
              name: "companyAddress",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
      ],
      inheritedFunctions: {},
    },
    Company: {
      address: "0xe7f1725e7734ce288f8367e1bb143e90bb3f0512",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_owner",
              type: "address",
              internalType: "address",
            },
            {
              name: "_companyPublicKey",
              type: "string",
              internalType: "string",
            },
            {
              name: "_name",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "acceptOffer",
          inputs: [
            {
              name: "_applicationId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "applicationCounter",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "applications",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "applicant",
              type: "address",
              internalType: "address",
            },
            {
              name: "jobId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "encryptedDataCID",
              type: "string",
              internalType: "string",
            },
            {
              name: "status",
              type: "uint8",
              internalType: "enum Company.ApplicationStatus",
            },
            {
              name: "gender",
              type: "uint8",
              internalType: "enum Company.Gender",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "companyPublicKey",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "completeAssessment",
          inputs: [
            {
              name: "_applicationId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "createJobListing",
          inputs: [
            {
              name: "_title",
              type: "string",
              internalType: "string",
            },
            {
              name: "_description",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "decryptionCounter",
          inputs: [
            {
              name: "",
              type: "uint8",
              internalType: "enum Company.Gender",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getApplication",
          inputs: [
            {
              name: "_applicationId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct Company.Application",
              components: [
                {
                  name: "applicant",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "jobId",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "encryptedDataCID",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "status",
                  type: "uint8",
                  internalType: "enum Company.ApplicationStatus",
                },
                {
                  name: "gender",
                  type: "uint8",
                  internalType: "enum Company.Gender",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getJobListing",
          inputs: [
            {
              name: "_jobId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct Company.JobListing",
              components: [
                {
                  name: "id",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "title",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "description",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "isActive",
                  type: "bool",
                  internalType: "bool",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "giveAssessment",
          inputs: [
            {
              name: "_applicationId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "grantDataAccess",
          inputs: [
            {
              name: "_applicationId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "jobCounter",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "jobListings",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "title",
              type: "string",
              internalType: "string",
            },
            {
              name: "description",
              type: "string",
              internalType: "string",
            },
            {
              name: "isActive",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "name",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "offerCounter",
          inputs: [
            {
              name: "",
              type: "uint8",
              internalType: "enum Company.Gender",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "releaseResults",
          inputs: [
            {
              name: "_applicationId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "sendOffer",
          inputs: [
            {
              name: "_applicationId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "submitApplication",
          inputs: [
            {
              name: "_jobId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_encryptedDataCID",
              type: "string",
              internalType: "string",
            },
            {
              name: "_gender",
              type: "uint8",
              internalType: "enum Company.Gender",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "updateJobListing",
          inputs: [
            {
              name: "_jobId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_title",
              type: "string",
              internalType: "string",
            },
            {
              name: "_description",
              type: "string",
              internalType: "string",
            },
            {
              name: "_isActive",
              type: "bool",
              internalType: "bool",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "ApplicationSubmitted",
          inputs: [
            {
              name: "applicationId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "applicant",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "jobId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "AssessmentCompleted",
          inputs: [
            {
              name: "applicationId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "AssessmentGiven",
          inputs: [
            {
              name: "applicationId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "DataAccessGranted",
          inputs: [
            {
              name: "applicationId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "JobListingCreated",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "title",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OfferAccepted",
          inputs: [
            {
              name: "applicationId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OfferSent",
          inputs: [
            {
              name: "applicationId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ResultsOut",
          inputs: [
            {
              name: "applicationId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
